#!/bin/bash
########
# Help #
########
Help()
{
   # Display Help
   echo "Canard Installation options:"
   echo "h     Print this Help"
   echo "m     Specify the machine"
   echo "l     Get a listed of registered machines"
   echo "v     Verbose mode [default OFF]"
   echo "d     Debug mode build type [default OFF]"
   echo "c     Specify compiler"
   echo "p     Specify MPI implementation"
   echo
}

List()
{
   echo "Registered and tested machines:"
   echo "$(ls -1 machine)"
}


########
# Main #
########
VERBOSE=OFF
BTYPE=Release
VISCOUS=OFF
OPENACC_GPU=OFF
MACHINE=
COMPILER=
while getopts ":hm:lvdc:p:" option; do
   case $option in
      h) # display Help
         Help
         exit;;
      m) # define machine
         MACHINE=${OPTARG}
	 echo "Using ${OPTARG} machine"
	 ;;
      l)  # List machines
	 List
	 exit;;
      v) # Verbose mode
	 VERBOSE=ON
	 ;;
      d) # Debug mode
	 BTYPE=Debug
	 ;;
      c) # Compiler
         COMPILER=${OPTARG}
         ;;
      p) # MPI
         MPI_TYPE=${OPTARG}
         ;;
     \?) # Invalid option
         echo "Error: Invalid option"
         exit;;
   esac
done

source machine/${MACHINE} ${COMPILER} ${MPI_TYPE}

mkdir build
cd build

echo "cmake -DCMAKE_INSTALL_PREFIX=${CANARD_DIR} -DCMAKE_BUILD_TYPE=${BTYPE} -DCMAKE_VERBOSE_MAKEFILE:BOOL=${VERBOSE} .."

cmake -DCMAKE_INSTALL_PREFIX=${CANARD_DIR}     \
      -DCMAKE_BUILD_TYPE=${BTYPE}              \
      -DCMAKE_VERBOSE_MAKEFILE:BOOL=${VERBOSE} \
      ..

make install
cd ..
rm -r build

